"-1, 0" = '''
MOV UP RIGHT
'''

"0, 0" = """
RST:MOV LEFT ACC
JNZ SK1
MOV 1 RIGHT
JMP RST
SK1:MOV 4 RIGHT
MOV ACC RIGHT
MOV ACC RIGHT
"""

"1, 0" = """
RST:JRO LEFT
MOV ACC RIGHT#1
MOV 0 ACC
JMP RST
SUB LEFT#4
JGZ SK1
MOV LEFT ACC
JMP RST
SK1:ADD LEFT
"""

"-1, -1" = [1, 3, 2, 5, 0]
